apiVersion: v1
kind: Secret
metadata:
    name: taskapp-secret
type: Opaque
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:2qW3mF0iz9g/RukiZNnuN4IWxIT9G7BZuNQ3BYb6ceKzTNbiX+3gGtYA8BjQbpZIHjhvpRyU38mZVAyAnmH/AE8=,iv:1QrU8FWznaHdppilkMZ6pT4jV+Z095W6HE/PW/rNy7c=,tag:9CYyRWO9lExVfynCEkcEfg==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:BV1fSg==,iv:6BeVKemyWhGgSc4dTOT3JvY9rfR2T7HWcGkdd4zXDwk=,tag:ea0DOO+AR6iSEdpuYkZCtg==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:twMs4ffy,iv:XJooPxiORFlETlMM1GhPmNuPrrjk+iGGXD2jREkUm28=,tag:dELyZyvAjEZr9SPXuU7TfA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:XYuweWTBN5A34va4JjzGW2I8SzufeahHwHuyypPhkMc7TWjIPqbg7DKs9m44OPHvUABczh7OqlhkKpskq4YQYVM=,iv:10Um6NDxAZuXkCndXEHqbVQzwbR1pkqWvQn4uOXfeVk=,tag:4iVR2A9rLsbNlFtTH2SANA==,type:str]
    JWT_EXPIRATION_MS: ENC[AES256_GCM,data:zOwQGwRF+aQ=,iv:OOzyj5rl9PvsMOWL4sEnAnxhPTUvUG5rdukgwvNPX58=,tag:yBafBCAwOZon+Cs1+p9+QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kfkuvkflsntqyr57zc3gkh2r9szx3qy7swyvjtxxddzhsq47shs973gls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWTZxdEJWVGRKVmhSZjU3
            eDd0TmtKd0dYb3hHQmNicjc2aDViY3RkbmdBCm1zeHZabUVGeE1BTGEyOWhnUHBs
            L2JvSmpRQytBQXBaREpCeEdQVGhyZDAKLS0tIHZ0TWdzRVc2eFpQdy8wWUsvQ1JP
            SVhicHY5OFY3ZzZreGloUnIyOHFnS2sK0N/Ha9o7DbGZGXZc+CNuVnVH0CRz9zAu
            V7l0R23o8DeztwekrmxCGH5iZ1eVscfdStAUxgoRWpXQhaLmnWiZbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T02:56:41Z"
    mac: ENC[AES256_GCM,data:5ejHMs8xCLtEArmo3bWonKaur1z3E6pp3XdYezW9M1E8iN+VuVHPdPdv5PPmxYgiZD1PK1HH6xeQ9JyLjLr44gVdDbnK6qSmguP7xbYbKBH1WYhlJoSiWN9zpczqMxAzWL8ZmfMRGJ/Zpqa3TFo/7wCbB5wgiFQvpV5kMsrj4f8=,iv:SQFjN5zsbDW0zZJD0wZz87ikMHIoLtdcygLbuW44KL4=,tag:1gAq2JSs4D7FfkfGwxBWIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
