apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/postgres

patches:
  - target:
      kind: StatefulSet
      name: postgres
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: postgres
      spec:
        replicas: 1